In [2]:
# Modules a group of functions,classes varibles saved to a file is called a modules

In [ ]:
# Advantages of Module

#1 Code re-useablity
#2 Better readablity
#3 Easy to maintain (add new functions)

In [ ]:
# import <module>
# import <module1>,<module2>,<module3>
# Access <moduleName>.method()
# for every module 

In [1]:
import math

In [3]:
math.factorial(3)

6

In [ ]:
# import <module> as <mm>
# import <module1> as mm1,<module2> as mm2
# where <mm> is the AliasName
#--------------------------------
#<mm>.members
#<mm>.methods()

In [4]:
import math as ma

In [5]:
ma.factorial(3)

6

In [ ]:
# To access directly the methods
# From <module> import method1
# From <module> import method1,method2,member1
# now we can use method1() -- Directly
# ie: method1()

In [6]:
from math import factorial

In [7]:
factorial(3)

6

In [8]:
from math import factorial,sqrt

In [9]:
sqrt(25)

5.0

In [ ]:
# From <module> import *
## In this case all are imported 

In [3]:
from math import *

In [4]:
factorial(4)

24

In [3]:
# To create Alias Name for Methods
# From <module> import method1 as mm1,method2 as mm2 
# ie: mm1()

In [ ]:
#__pychache__

# Relaoding Module

In [3]:
# reloading modules

In [1]:
from imp import reload

In [ ]:
#to load the latest module
#reload(<modulename>)

# using relaoding we get the latest version 

# dir() Function

In [ ]:
# dir function: pyhton uses this function to list all the functions of module

In [2]:
#dir(): all members of current modules

In [7]:
x = 10
y = 20
def f1(x1,y1):
    print("Adding :",x1+y1)
f1(10,30)

Adding : 40


In [21]:
import numpy as np

In [18]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [6]:
import math

In [7]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [8]:
import pandas

In [20]:
dir(pandas)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Panel4D',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseList',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p8',
 '_np_version_under1p9',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'describ

In [22]:
dir()

['In',
 'Out',
 '_',
 '_18',
 '_2',
 '_20',
 '_4',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'f1',
 'get_ipython',
 'np',
 'numpy',
 'pandas',
 'quit',
 'x',
 'y']

In [ ]:
#ques __name__ : 

# working with math module

In [24]:
from math import *

In [31]:

a =  numpy.random.randint(1,100,30)
for i in a:
    print(sqrt(i))

9.38083151964686
8.602325267042627
8.18535277187245
4.898979485566356
8.18535277187245
9.695359714832659
4.795831523312719
9.055385138137417
3.3166247903554
9.219544457292887
7.615773105863909
9.16515138991168
6.557438524302
5.656854249492381
8.306623862918075
8.06225774829855
6.557438524302
4.0
6.782329983125268
8.18535277187245
5.0
4.69041575982343
8.246211251235321
9.746794344808963
7.745966692414834
9.0
1.4142135623730951
9.486832980505138
7.937253933193772
3.872983346207417


In [28]:
a =  numpy.random.randint(1,25,10)

array([18, 15, 16, 16, 24,  5, 15,  3,  3, 18])

In [33]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [36]:
help(pandas)

Help on package pandas:

NAME
    pandas

DESCRIPTION
    pandas - a powerful data analysis and manipulation library for Python
    
    **pandas** is a Python package providing fast, flexible, and expressive data
    structures designed to make working with "relational" or "labeled" data both
    easy and intuitive. It aims to be the fundamental high-level building block for
    doing practical, **real world** data analysis in Python. Additionally, it has
    the broader goal of becoming **the most powerful and flexible open source data
    analysis / manipulation tool available in any language**. It is already well on
    its way toward this goal.
    
    Main Features
    -------------
    Here are just a few of the things that pandas does well:
    
      - Easy handling of missing data in floating point as well as non-floating
        point data
      - Size mutability: columns can be inserted and deleted from DataFrame and
        higher dimensional objects
      - Automatic and

In [38]:
import time
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'perf_counter',
 'process_time',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'time',
 'timezone',
 'tzname',
 'tzset']

# workin with random module

In [9]:
import random as rd

In [10]:
import numpy as np

In [5]:
rd.randint(0,100)

98

In [9]:
a = np.random.randint(1,10,7)
a

array([7, 5, 9, 4, 3, 9, 5])

In [11]:
def getcode():
    a = np.random.randint(1,10,7)
    x = ""
    for i in a:
        if x == "":
            x = str(i)
        else:
            x = x + str(i)
    return int(x)

In [13]:
getcode()

8637177

In [43]:
la = lambda a:np.random.randint(100000,999999,a)

In [49]:
x = la(11)
x

array([504145, 575354, 683291, 497871, 910492, 928602, 238090, 388368,
       652583, 355351, 549957])

In [32]:
x = np.random.randint(100000,999999,1)
val = x[0]
val

910487

In [51]:
from random import *
#random function generates numbers betwwen 0 and 1
for i in range(10):
    print(random())

0.5594652999905019
0.9888336414113956
0.5340149939355925
0.9581831300745184
0.398698992727774
0.1285526072978218
0.3488259327908536
0.598383071604495
0.37239053133297695
0.7093923749872227


In [17]:
# int b/w 1 and 100
rd.randint(1000000,9999999)

1648211

In [13]:
def getsecretcodex():
    return rd.randint(10000,99999)

In [18]:
codes = []
for i in range(10):
    codes.append(getsecretcodex())

In [19]:
codes

[23640, 20055, 31079, 62252, 24694, 97054, 40968, 88628, 54924, 44884]

In [143]:
for i in range(10):
    print(getsecretcodex())
    

88115
36150
25291
22638
14118
80255
95138
36701
15013
19101


In [87]:
type(a)

int

In [ ]:
# float b/w 1,2
#uniform


In [52]:
for i in range(10):
    print(uniform(1,3))

2.556602499905541
1.7967563932058177
1.3337964006295415
2.0527711374769195
2.6611865451937406
2.3542044354887253
2.457636979163275
2.270497166731162
1.5307117756122286
2.523348276251483


In [53]:
dir(random)
#help(random)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [ ]:
#random(x,y) not incluslive of x,y
#randint(x,y) inclusive of x,y
#uniform(x,y) not incluslive of x,y

In [102]:
randrange(1,10) # start is incluslive of x and y is exclusive

6

In [117]:
#choice function : wont return random number it will retrun random obj from a given list
# any indexable sequence

In [13]:
a = np.random.randint(1,100,10)
print(rd.choice(a))

76


In [105]:
print(choice(a))

12


In [109]:
print(choice(a))

36


In [110]:
a

array([36, 94, 55, 11, 27, 85, 12, 29, 76, 88])

In [111]:
t = (36, 94, 55, 11, 27, 85, 12, 29, 76, 88)

In [116]:
choice(t),choice(t),choice(t),choice(t)

(12, 36, 27, 29)

In [10]:
name = "Sashank Ragireddy"
choice(name)

NameError: name 'choice' is not defined

In [123]:
def getcodex():
    

20

In [148]:
chr(randint(65,90))

'J'

# Package

In [ ]:
# Package: Encapsulation of files is called package with __init__.py
# however not required from python 3.3
# implicit namespaces are now available

In [149]:
#adv 
#1 naming conflicts resolved
#2 modularity
#3 readable and easy to maintain
#4 unique identifires

In [150]:
pwd

'/Users/shashankragireddy/Python/01-Python NoteBooks'

In [151]:
# Naming conventon for python
# reverse of client internet domain name 

# library

In [152]:
# a group of packages is called library

In [ ]:
#com.icicibank.loan.homeloan.action()